### PR TITLE
Acpears pokeball blocks feature

### PR DESCRIPTION
**Pull request by acpears**
- Mod now includes 3 blocks
- Loot tables have been created for these blocks such that they will drop redstone when broken with a diamond pickaxe. If not the blocks will drop themselves.
- Eventually each colored block will drop a colored pokeball once the pokeball item feature has been added

### CODE REVIEW

**Comment by yum-feng** [comment]
Yop! Nice work.

Just a few naming proposals:
 - Would it be OK in renaming the `PokeballBlock` -> `PokeBallOreBlock`?
 - Additionally, could we change the table name `Pokemon Animals` -> `Pokebies` ?

If I am understanding correctly, the logic behind blocks dropping certain items is actually just a configuration file that is being statically generated by the file `src/main/java/teamzombie/pokez/datagen/ModLootTable.java`?

**Comment by acpears** [comment]
> 

No problem for the renaming. I like the suggestions :)

Yes it is simply a .json config file. Everything under the datagen package is about generating these configurations files. You could technically write them manually by hand but forge gives you functionality to have them generated. This is what is found under datagen. For the blocks dropping items, yes that is table created by `src/main/java/teamzombie/pokez/datagen/ModLootTable.java` which itself uses specific methods from `src/main/java/teamzombie/pokez/datagen/BaseLootTableProvider.java`. Most of the work is done in this file!

**Review by rahuselama — COMMENTED** [review]
can we merge it now?

**Comment by yum-feng** [comment]
> can we merge it now?

I think Adam is preparing some new changes. The pull request shows a timeline of activities, and I haven't seen any commits since his reply.

**Comment by acpears** [comment]
> > can we merge it now?
> 
> I think Adam is preparing some new changes. The pull request shows a timeline of activities, and I haven't seen any commits since his reply.

Done! We would be able to move onto the next step in the workflow

**Comment by yum-feng** [comment]
lgtm!

**Review by yum-feng — APPROVED** [review]

**Pull request merged**
